name: certbot-nginx-unit
summary: Certbot plugin for Nginx Unit
description: |
  Certbot plugin provides HTTP challenge and installation of certificates.
  Support multi-domain and renew.
  See https://github.com/kea/certbot-nginx-unit for installation and usage instructions.
confinement: strict
grade: stable
base: core24
adopt-info: certbot-nginx-unit
license: MIT
website: https://github.com/kea/certbot-nginx-unit
issues: https://github.com/kea/certbot-nginx-unit/issues

platforms:
  amd64:
  armhf:
  arm64:

parts:
  certbot-nginx-unit:
    plugin: python
    source: .
    override-build: |
      craftctl build
      craftctl set version=$(grep " version =" $CRAFT_PART_BUILD/version.py | cut -f3 -d= | tr -d "'[:space:]")
    build-packages:
      - git
    build-environment:
      - SNAP_BUILD: "True"
  certbot-metadata:
    plugin: dump
    source: .
    stage: [ setup.py, certbot-shared ]
    override-pull: |
      craftctl default
      mkdir -p $CRAFT_PART_SRC/certbot-shared

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.12/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
